# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.generate_frequency_table <- function(head_seq, seq_id, seq_size, ws, cut_off, motifs, k) {
    .Call(`_DNAmotif_generate_frequency_table`, head_seq, seq_id, seq_size, ws, cut_off, motifs, k)
}

